// build.rs — Pre-rasterize IBM Plex Mono at multiple sizes using fontdue
// Generates oled_fonts_gen.rs with const glyph coverage data for anti-aliased rendering

use fontdue::{Font, FontSettings};
use std::env;
use std::fs;
use std::path::Path;

// Font sizes to rasterize (in pixels)
const SIZES: &[(u8, &str, &str)] = &[
    (11, "SMALL", "Regular"),      // labels (CH, PAT, LOOP, KEY, SCALE)
    (11, "SMALL_BOLD", "Bold"),    // values at same size, bold weight
    (14, "MEDIUM", "Bold"),        // larger values
    (18, "LARGE", "Bold"),         // emphasized values
    (24, "COF", "Bold"),           // circle of fifths key letter
    (40, "XLARGE", "Bold"),        // dial note letter
];

// ASCII range to rasterize
const FIRST_CHAR: u8 = 0x20; // space
const LAST_CHAR: u8 = 0x7E;  // tilde

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("oled_fonts_gen.rs");

    let assets = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets");
    let regular_data = fs::read(assets.join("IBMPlexMono-Regular.ttf")).expect("Regular font");
    let bold_data = fs::read(assets.join("IBMPlexMono-Bold.ttf")).expect("Bold font");

    let regular = Font::from_bytes(regular_data.as_slice(), FontSettings::default()).unwrap();
    let bold = Font::from_bytes(bold_data.as_slice(), FontSettings::default()).unwrap();

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit\n");
    out.push_str("// IBM Plex Mono pre-rasterized glyph data with coverage (alpha) values\n\n");
    out.push_str("use crate::oled_gfx::AAGlyph;\n\n");

    for &(size, name, weight) in SIZES {
        let font = match weight {
            "Bold" => &bold,
            _ => &regular,
        };
        generate_font_data(&mut out, font, size, name);
    }

    fs::write(&dest_path, out).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=assets/IBMPlexMono-Regular.ttf");
    println!("cargo:rerun-if-changed=assets/IBMPlexMono-Bold.ttf");
}

fn generate_font_data(out: &mut String, font: &Font, size: u8, name: &str) {
    let px = size as f32;

    // Collect all glyph bitmaps
    let mut all_coverage: Vec<u8> = Vec::new();
    let mut glyphs: Vec<(u16, u8, u8, u8, i8, i8)> = Vec::new(); // offset, w, h, x_advance, x_off, y_off

    // Get line metrics for baseline
    let line_metrics = font.horizontal_line_metrics(px).unwrap();
    let ascent = line_metrics.ascent.round() as i16;

    for ch in FIRST_CHAR..=LAST_CHAR {
        let (metrics, bitmap) = font.rasterize(ch as char, px);

        let offset = all_coverage.len() as u16;
        let w = metrics.width as u8;
        let h = metrics.height as u8;
        let x_advance = metrics.advance_width.round() as u8;
        // fontdue: xmin = left bearing, ymin = descent below baseline
        let x_offset = metrics.xmin as i8;
        // Convert fontdue's ymin to top-relative y_offset
        // fontdue ymin = pixels below baseline (positive = above)
        let y_offset = (-(metrics.ymin as i16) - (metrics.height as i16) + ascent) as i8;

        all_coverage.extend_from_slice(&bitmap);
        glyphs.push((offset, w, h, x_advance, x_offset, y_offset));
    }

    // Write coverage data
    out.push_str(&format!(
        "static FONT_{}_COVERAGE: [u8; {}] = [\n    ",
        name,
        all_coverage.len()
    ));
    for (i, &b) in all_coverage.iter().enumerate() {
        out.push_str(&format!("0x{:02X},", b));
        if (i + 1) % 20 == 0 {
            out.push_str("\n    ");
        }
    }
    out.push_str("\n];\n\n");

    // Write glyph table
    let glyph_count = glyphs.len();
    out.push_str(&format!(
        "static FONT_{}_GLYPHS: [AAGlyph; {}] = [\n",
        name, glyph_count
    ));
    for (offset, w, h, x_advance, x_off, y_off) in &glyphs {
        out.push_str(&format!(
            "    AAGlyph {{ coverage_offset: {}, width: {}, height: {}, x_advance: {}, x_offset: {}, y_offset: {} }},\n",
            offset, w, h, x_advance, x_off, y_off
        ));
    }
    out.push_str("];\n\n");

    // Write font struct
    out.push_str(&format!(
        "pub static FONT_AA_{}: crate::oled_gfx::AAFont = crate::oled_gfx::AAFont {{\n",
        name
    ));
    out.push_str(&format!("    coverage: &FONT_{}_COVERAGE,\n", name));
    out.push_str(&format!("    glyphs: &FONT_{}_GLYPHS,\n", name));
    out.push_str(&format!("    first: 0x{:02X},\n", FIRST_CHAR));
    out.push_str(&format!("    last: 0x{:02X},\n", LAST_CHAR));
    let y_advance = (px * 1.3).round() as u8;
    out.push_str(&format!("    y_advance: {},\n", y_advance));
    out.push_str("};\n\n");
}
